name: Verificar Nombres de Archivos
on: [workflow_call]

jobs:
  check-js-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Listar archivos JavaScript
        run: |
          echo "üìÅ Archivos JavaScript encontrados:"
          cd ejercicios-js/
          for file in *.js; do
            if [ -f "$file" ]; then
              echo "‚úÖ $file"
            fi
          done

  check-py-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Listar archivos Python
        run: |
          echo "üìÅ Archivos Python encontrados:"
          cd ejercicios-py/
          for file in *.py; do
            if [ -f "$file" ]; then
              echo "‚úÖ $file"
            fi
          done